# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.27

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ket/code/c/networking/tcp_chat

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ket/code/c/networking/tcp_chat

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ket/code/c/networking/tcp_chat/CMakeFiles /home/ket/code/c/networking/tcp_chat//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ket/code/c/networking/tcp_chat/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named userauth

# Build rule for target.
userauth: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 userauth
.PHONY : userauth

# fast build rule for target.
userauth/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/userauth.dir/build.make CMakeFiles/userauth.dir/build
.PHONY : userauth/fast

#=============================================================================
# Target rules for targets named tcp_chat

# Build rule for target.
tcp_chat: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tcp_chat
.PHONY : tcp_chat

# fast build rule for target.
tcp_chat/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_chat.dir/build.make CMakeFiles/tcp_chat.dir/build
.PHONY : tcp_chat/fast

src/app.o: src/app.c.o
.PHONY : src/app.o

# target to build an object file
src/app.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_chat.dir/build.make CMakeFiles/tcp_chat.dir/src/app.c.o
.PHONY : src/app.c.o

src/app.i: src/app.c.i
.PHONY : src/app.i

# target to preprocess a source file
src/app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_chat.dir/build.make CMakeFiles/tcp_chat.dir/src/app.c.i
.PHONY : src/app.c.i

src/app.s: src/app.c.s
.PHONY : src/app.s

# target to generate assembly for a file
src/app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tcp_chat.dir/build.make CMakeFiles/tcp_chat.dir/src/app.c.s
.PHONY : src/app.c.s

src/user_auth.o: src/user_auth.c.o
.PHONY : src/user_auth.o

# target to build an object file
src/user_auth.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/userauth.dir/build.make CMakeFiles/userauth.dir/src/user_auth.c.o
.PHONY : src/user_auth.c.o

src/user_auth.i: src/user_auth.c.i
.PHONY : src/user_auth.i

# target to preprocess a source file
src/user_auth.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/userauth.dir/build.make CMakeFiles/userauth.dir/src/user_auth.c.i
.PHONY : src/user_auth.c.i

src/user_auth.s: src/user_auth.c.s
.PHONY : src/user_auth.s

# target to generate assembly for a file
src/user_auth.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/userauth.dir/build.make CMakeFiles/userauth.dir/src/user_auth.c.s
.PHONY : src/user_auth.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... tcp_chat"
	@echo "... userauth"
	@echo "... src/app.o"
	@echo "... src/app.i"
	@echo "... src/app.s"
	@echo "... src/user_auth.o"
	@echo "... src/user_auth.i"
	@echo "... src/user_auth.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

